### ISSUE TITLE
Netdata-TSRelay broken?

### ISSUE THREAD

**Issue by bjoe2k4** [mahlonsmith/netdata-timescale-relay#2] opened 2020-07-11 23:08 UTC
Hi @mahlonsmith 

i've just come to try this tool, however i cannot get it to work.

I'm using ArchLinux x64, which currently features nim v1.2.0. At the time of the latest release, nim v0.19.0 was the most recent. 

Compilation gives some warnings but it builds fine:

```
[mpkg@zink netdata-timescale-relay]$ make
nim -d:release --opt:speed --parallelBuild:0 --nimcache:.cache c netdata_tsrelay.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: netdata_tsrelay [Processing]
Hint: db_postgres [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: postgres [Processing]
Hint: db_common [Processing]
Hint: json [Processing]
Hint: hashes [Processing]
Hint: tables [Processing]
Hint: lexbase [Processing]
Hint: streams [Processing]
Hint: parsejson [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: nativesockets [Processing]
Hint: os [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: posix [Processing]
Hint: times [Processing]
Hint: net [Processing]
Hint: sets [Processing]
Hint: monotimes [Processing]
Hint: ssl_certs [Processing]
Hint: ospaths [Processing]
Hint: parseopt [Processing]
Hint: terminal [Processing]
Hint: strformat [Processing]
Hint: colors [Processing]
Hint: termios [Processing]
/home/mpkg/netdata-timescale-relay/netdata_tsrelay.nim(201, 27) Warning: use strformat module instead; round is deprecated [Deprecated]
/home/mpkg/netdata-timescale-relay/netdata_tsrelay.nim(37, 5) Warning: imported and not used: 'os' [UnusedImport]
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_formatfloat.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: stdlib_parseutils.nim
CC: stdlib_math.nim
CC: stdlib_unicode.nim
CC: stdlib_strutils.nim
CC: stdlib_postgres.nim
CC: stdlib_db_common.nim
CC: stdlib_db_postgres.nim
CC: stdlib_hashes.nim
CC: stdlib_tables.nim
CC: stdlib_streams.nim
CC: stdlib_lexbase.nim
CC: stdlib_parsejson.nim
CC: stdlib_options.nim
CC: stdlib_json.nim
CC: stdlib_times.nim
CC: stdlib_os.nim
CC: stdlib_nativesockets.nim
CC: stdlib_monotimes.nim
CC: stdlib_net.nim
CC: stdlib_parseopt.nim
CC: stdlib_terminal.nim
CC: netdata_tsrelay.nim
Hint:  [Link]
Hint: 71950 LOC; 2.961 sec; 73.398MiB peakmem; Release build; proj: /home/mpkg/netdata-timescale-relay/netdata_tsrelay.nim; out: /home/mpkg/netdata-timescale-relay/netdata_tsrelay [SuccessX]
```

However when setup, i'm not getting my timescaledb populated. The relay logs the following:

```
sudo -u netdata /usr/local/bin/netdata_tsrelay -d --listen-addr=127.0.0.1                                                      ✔  0.008s  /etc/netdata  23:35:35
(dbopts: "host=localhost dbname=netdata application_name=netdata-tsrelay", dbtable: "netdata", listen_port: 14866, listen_addr: "127.0.0.1", verbose: true, debug: true, insertsql: "    INSERT INTO netdata\n        ( time, host, metrics )\n    VALUES\n        ( \'epoch\'::timestamptz + ? * \'1 second\'::interval, ?, ? )\n    ", timeout: 500)
Successfully tested connection to the backend database.
Listening for incoming connections on 127.0.0.1:14866

1594503365 0 sample(s) parsed from 127.0.0.1 in 0.0 seconds.
1594503425 0 sample(s) parsed from 127.0.0.1 in 0.0 seconds.
1594503485 0 sample(s) parsed from 127.0.0.1 in 0.0 seconds.
1594503545 0 sample(s) parsed from 127.0.0.1 in 0.0 seconds.
1594503605 0 sample(s) parsed from 127.0.0.1 in 0.0 seconds.
1594503665 0 sample(s) parsed from 127.0.0.1 in 0.0 seconds.
1594503725 0 sample(s) parsed from 127.0.0.1 in 0.0 seconds.
1594503785 0 sample(s) parsed from 127.0.0.1 in 0.0 seconds.
1594503845 0 sample(s) parsed from 127.0.0.1 in 0.0 seconds.
...
```

Depending on how much metrics i send, i'm getting different error messages in netdata's error.log:

"Many metrics":
```
netdata ERROR : MAIN : EXPORTING: failed to write data to '127.0.0.1:14866'. Willing to write 685507 bytes, wrote 524288 bytes. Will re-connect.
```

"Little metrics":
```
netdata ERROR : MAIN : EXPORTING: '127.0.0.1:14866' closed the socket
```

My exporting.conf (netdata v1.23.1) contains the following:
```
[exporting:global]
    enabled = yes

[json:timescaledb]
    hostname           = zink
    enabled            = yes
    type               = json
    data source        = average
    destination        = 127.0.0.1:14866
    prefix             = netdata
    update every       = 60
    buffer on failures = 10
    send charts matching = *
    send hosts matching = *
```

Any suggestions appreciated!

**Comment by mahlonsmith** [comment] 2020-07-14 19:35
I hadn't noticed that Netdata deprecated the 'backend' configuration.

"Please be aware that backends subsystem is deprecated and Netdata configuration should be moved to the new exporting conf configuration file."

If I use the backend style conf, things still work -- However I can indeed replicate your issue using the new `exporting.conf` format, implying that something was altered along the way.  Doing some more digging.

**Comment by bjoe2k4** [comment] 2020-07-14 20:04
Might the problem be that you are closing the tcp connection? While reimplementing this thing in python last weekend, I've noticed that netdata will connect, but not send any data right away. Instead it would send twice the amount of data after another `update every` interval.

**Comment by mahlonsmith** [comment] 2020-07-25 22:34
Finally got a chance to dig into this today, thanks for the patience.  You're correct, it is related to closing the socket.

Since netdata doesn't send a length, nor a delimiter between sample sends, I'm using the pause as the trigger to write the sample(s) to database.  The default behavior of the relay was to scratch my itch in my specific environment - I've pushed an update that exposes some new knobs relating to tcp connection and postgresql handles, and changes the default behavior to leave the socket open.   Should help in the case where you are only collecting from a small handful of hosts.

https://github.com/mahlonsmith/netdata-timescale-relay/releases/tag/v0.3.0

At much larger scale (aside from -definitely- using a pooler) where you might want to conserve local file descriptors / process counts, there's a separate issue now where every other sample is dropped.  I think the new behavior is surprising and have filed a ticket with netdata - leaving this ticket open in the interim.

https://github.com/netdata/netdata/issues/9607

Thanks for the heads up on this.

**Comment by mahlonsmith** [comment] 2020-12-11 00:24
Confirmed today that both older versions (1.13.x), along with newer versions (1.26.x) using both the deprecated config or the `exporting.conf` work properly.  Closin'!

**Closed as completed by mahlonsmith** 2020-12-11 00:24 UTC
Labels: bug
